"""initial

Revision ID: 216b77b7250b
Revises: 
Create Date: 2025-05-05 22:27:07.226337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216b77b7250b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_update_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_successful_update', sa.DateTime(), nullable=True),
    sa.Column('next_scheduled_update', sa.DateTime(), nullable=True),
    sa.Column('is_updating', sa.Boolean(), nullable=True),
    sa.Column('teams_updated', sa.Boolean(), nullable=True),
    sa.Column('players_updated', sa.Boolean(), nullable=True),
    sa.Column('games_updated', sa.Boolean(), nullable=True),
    sa.Column('current_phase', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('last_error_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('loading_progress', sa.Integer(), nullable=True),
    sa.Column('roster_loaded', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_date_utc', sa.DateTime(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('season_year', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.Column('previous_team_id', sa.Integer(), nullable=True),
    sa.Column('traded_date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('jersey_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('headshot_url', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['previous_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_game_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tp_pct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'game_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game_stats')
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('data_update_status')
    # ### end Alembic commands ###
