"""add_playoff_round_to_games

Revision ID: b3bd645a3067
Revises: f6284cfa10b7
Create Date: 2025-05-09 22:23:26.590903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bd645a3067'
down_revision: Union[str, None] = 'f6284cfa10b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('playoff_round', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'playoff_round')
    # ### end Alembic commands ###
