"""add games_loaded to teams

Revision ID: efd93d7f13c5
Revises: 216b77b7250b
Create Date: 2025-05-06 15:00:35.770809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd93d7f13c5'
down_revision: Union[str, None] = '216b77b7250b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('games_loaded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'games_loaded')
    # ### end Alembic commands ###
