version: '3.8'

services:
  backend:
    build: ./Application/backend
    container_name: nba_stats_backend
    ports:
      - "7778:7778"
    volumes:
      - nba_stats_data:/app/data
    environment:
      - HOST=0.0.0.0
      - NBA_STATS_DATA_DIR=/app/data

  frontend:
    build: ./Application/frontend
    container_name: nba_stats_frontend
    ports:
      - "7779:7779"
    depends_on:
      - backend

volumes:
  nba_stats_data: