services:
  frontend:
    build: ./Application/frontend
    ports:
      - "7779:7779"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - nba_network
    restart: unless-stopped

  backend:
    build: ./Application/backend
    expose:
      - "7778"
    volumes:
      - nba_data:/app/data
    networks:
      - nba_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7778/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: unless-stopped

networks:
  nba_network:
    driver: bridge

volumes:
  nba_data: