version: '3.8'

services:
  backend:
    build: 
      context: ./Application/backend
      dockerfile: Dockerfile
      no_cache: true
    container_name: nba_stats_backend
    restart: unless-stopped
    ports:
      - "0.0.0.0:7778:7778"
    volumes:
      - nba_stats_data:/app/data
    environment:
      - HOST=0.0.0.0
      - NBA_STATS_DATA_DIR=/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7778/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./Application/frontend
      dockerfile: Dockerfile
      no_cache: true
    container_name: nba_stats_frontend
    restart: unless-stopped
    ports:
      - "0.0.0.0:7779:7779"
    environment:
      - VITE_API_URL=http://backend:7778
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7779"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nba_stats_data:
    name: nba_stats_data

networks:
  default:
    name: nba_stats_network