version: '3.8'

services:
  backend:
    build: ./Application/backend
    ports:
      - "7778:7778"
    volumes:
      - nba_stats_data:/app/data
    networks:
      - nba_network

  frontend:
    build: ./Application/frontend
    ports:
      - "7779:7779"
    depends_on:
      - backend
    networks:
      - nba_network

networks:
  nba_network:
    driver: bridge

volumes:
  nba_stats_data: