version: '3'

services:
  backend:
    build: ./Application/backend
    container_name: nba_stats_backend
    ports:
      - "7778:7778"
    volumes:
      - nba_stats_data:/app/data

  frontend:
    build: ./Application/frontend
    container_name: nba_stats_frontend
    ports:
      - "7779:7779"

volumes:
  nba_stats_data: