version: '3.8'

services:
  backend:
    build:
      context: ./Application/backend
      dockerfile: Dockerfile
    ports:
      - "7778:7778"
    volumes:
      - nba_stats_data:/app/data
    networks:
      - nba_network

  frontend:
    build:
      context: ./Application/frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "7779:7779"
    depends_on:
      - backend
    networks:
      - nba_network

networks:
  nba_network:
    driver: bridge

volumes:
  nba_stats_data: