version: '3.8'

services:
  backend:
    build: 
      context: ./Application/backend
      dockerfile: Dockerfile
    container_name: nba_stats_backend
    restart: unless-stopped
    ports:
      - "7778:7778"
    volumes:
      - ./Application/backend/nba_stats.db:/app/nba_stats.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7778/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./Application/frontend
      dockerfile: Dockerfile
    container_name: nba_stats_frontend
    restart: unless-stopped
    ports:
      - "7779:7779"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7779"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: nba_stats_network